#
# SPDX-FileCopyrightText: 2020 Dmytro Kolomoiets <amerlyq@gmail.com> and contributors.
#
# SPDX-License-Identifier: MIT
#

ssh_exe = /usr/bin/ssh
ssh_cfg = /dev/null
ssh_host = root@localhost
ssh_port = 2222


# THINK: how about scp, sshfs ?


.PHONY: ssh
#%ALIAS: [filesystem]
ssh: ssh-qemu     # login into qemu


# WARN: dropbear key is different each time HACK: disable checking
# NEED::(paswordless login): PermitEmptyPasswords yes (dropbear sshd_config)
# ALT: directly insert your id_rsa.pub >> authorized_hosts <= inside squashfs generated by buildroot
ssh-qemu: $(ssh_cfg) | $(ssh_exe)
	'$|'$(if $<, -F '$<')$(if $<, -p '$(ssh_port)') \
	  -o UserKnownHostsFile=/dev/null \
	  -o StrictHostKeyChecking=no \
	  -- $(ssh_host)
