#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2019 Dmytro Kolomoiets <amerlyq@gmail.com> and contributors.
#
# SPDX-License-Identifier: MIT
#
#%SUMMARY: get project version from git
#%USAGE: $ ./$0 [/path/to/dir..]
#%
set -r -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

d_git=${1-}
onlynumbers=${2:+1}

## ALT: use date of last commit
#   git --no-pager log --pretty=format:'%ad' --date=short -1 || echo 0
# OR: rev=$("${git[@]}" rev-list --count HEAD -- '^master')

## ALSO:IDEA: add full hash of each submodule to embed it into ELF
#  -DGIT_SHA_<PROJECT>=$(git rev-parse --verify --default HEAD)
#  => makes it possible to reproduce the same build in the same controllable environment

tag=$(git ${d_git:+-C "$d_git"} describe --always --dirty --tags --match '*.*.*')
tag=${tag/-/.}

((onlynumbers)) && tag=$(<<<"$tag" sed -rn '1s/^(^[0-9]+\.[0-9]+(\.[0-9]+)?([.-][0-9]+)?).*/\1/p')

if [[ -z $tag ]]; then
  echo "Must have at least one symver tag for versioning to work" \
    "( e.g. add tag by 'git tag 0.0.1' )"
  exit 1
fi

echo "$tag"
