#!/bin/sh
#
# SPDX-FileCopyrightText: 2019 Dmytro Kolomoiets <amerlyq@gmail.com> and contributors.
#
# SPDX-License-Identifier: Apache-2.0
#
#%SUMMARY: complex hook to verify quality of new commits
#%USAGE: $ install -Dm755 "$0" "$(git rev-parse --git-dir)/hooks"
#%
set -fCeu
exec make check-all
