#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2019 Dmytro Kolomoiets <amerlyq@gmail.com> and contributors.
#
# SPDX-License-Identifier: Apache-2.0
#
#%SUMMARY: cosmetic fixes to new commits
#%USAGE: $ install -Dm755 "$0" "$(git rev-parse --git-dir)/hooks"
#%
set -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

make aspell
make spell

# HACK: suppress output unless got error
tmp=$(make reuse) || { >&2 cat <<< "$tmp"; exit 1; }

# WARN: source code in workdir is reformatted BUT! commit is unchanged
#   => (intentionally) manually amend your commit OR make new commit with style format
make fmt
